installAndCheck <- function(pkg, dependencies=NA) {
    install.packages(pkg, dependencies=dependencies)
    if (pkg %in% installed.packages()) {
        print(paste(pkg, "was installed successfully"))
    } else {
        print(paste(pkg, "is not installed"))
        q("no", 1)
    }
}

installAndCheck("shiny")
installAndCheck("shinyBS")
installAndCheck("shinythemes")
installAndCheck("readxl")
installAndCheck("tidyverse")
installAndCheck("mi")
installAndCheck("descr")
installAndCheck("pROC")
installAndCheck("readxl")
installAndCheck("plyr")
installAndCheck("tidyverse")
installAndCheck("assertthat")
installAndCheck("ggplot2")
installAndCheck("cowplot")
installAndCheck("viridis")
installAndCheck("ggthemes")
installAndCheck("car")
installAndCheck("ggExtra")
installAndCheck("scales")
installAndCheck("xtable")
installAndCheck("markdown")
installAndCheck("htmltools")
installAndCheck("rsconnect")
installAndCheck("rmeta")
# New stuff for https://github.com/FredHutch/KInhibition
installAndCheck("shiny.semantic")
installAndCheck("DT")
installAndCheck("dplyr")
installAndCheck("plotly")
installAndCheck("webshot")
installAndCheck("reshape2")
installAndCheck("htmlwidgets")
installAndCheck("maps")
installAndCheck("mapproj")
# New stuff for https://github.com/adamssv/u025_1
installAndCheck("methods")
installAndCheck("bitops")
# New stuff for genomics-repo-app
installAndCheck("data.table", dependencies=TRUE) 
installAndCheck("shinythemes") 
installAndCheck("httr") 
installAndCheck("jsonlite")
installAndCheck("REDCapR") 
installAndCheck("aws.s3")
# New stuff for https://github.com/FredHutch/hawnmtb
installAndCheck("igraph")
installAndCheck("intergraph")
installAndCheck("ggnetwork")
